# Generated by Django 5.1.4 on 2025-01-02 20:44

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='タイトル')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='説明')),
                ('document_url', models.URLField(blank=True, null=True, verbose_name='ドキュメントURL')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHubURL')),
                ('is_public', models.BooleanField(default=True, verbose_name='公開設定')),
                ('members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
