# Generated by Django 5.1.4 on 2025-01-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Draft', '下書き'), ('Todo', '下書き'), ('In Progress', '進行中'), ('Done', '完了')], default='Draft', max_length=20),
        ),
    ]
